# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/NYTimes/gziphandler";
    fetch = {
      type = "git";
      url = "https://github.com/NYTimes/gziphandler";
      rev = "5032c8878b9dd46cfe8c625c0d9b9f258a560ee8";
      sha256 = "1avn8xb78xmmc61fjycpc81yrkfi42fna8zgzdqba6v7g8gq8a3x";
    };
  }
  {
    goPackagePath = "github.com/fgrosse/graphigo";
    fetch = {
      type = "git";
      url = "https://github.com/fgrosse/graphigo";
      rev = "5770fe631d9a4eef82623c6ee9425ee98ad1aeb1";
      sha256 = "1d0qazad1x4p492azbr973jm5d4x2r9fsq9ln4z3j2qyl2cm6ir2";
    };
  }
  {
    goPackagePath = "github.com/influxdata/influxdb";
    fetch = {
      type = "git";
      url = "https://github.com/influxdata/influxdb";
      rev = "375eddebb83c3f2d198d7a029363eeadc28f5a60";
      sha256 = "03ndfnri829ilz57w8sj646mj6x82ab9d6m20frzm3hqxczyrlxn";
    };
  }
  {
    goPackagePath = "github.com/naoina/go-stringutil";
    fetch = {
      type = "git";
      url = "https://github.com/naoina/go-stringutil";
      rev = "6b638e95a32d0c1131db0e7fe83775cbea4a0d0b";
      sha256 = "00831p1wn3rimybk1z8l30787kn1akv5jax5wx743nn76qcmkmc6";
    };
  }
  {
    goPackagePath = "github.com/naoina/toml";
    fetch = {
      type = "git";
      url = "https://github.com/naoina/toml";
      rev = "9fafd69674167c06933b1787ae235618431ce87f";
      sha256 = "0mpvdnidgab48k7dfq1vaiz1wny8n29y7zxpipnp1zm8ibxpism0";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "816c9085562cd7ee03e7f8188a1cfd942858cded";
      sha256 = "1ws5crb7c70wdicavl6qr4g03nn6m92zd6wwp9n2ygz5c8rmxh8k";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "a114f312e075f65bf30d6d9a1430113f857e543b";
      sha256 = "10lmi5ni06yijxg02fcic5b7ycjkia12yma4a4lz8a56j30wykx1";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "3ebe029320b2676d667ae88da602a5f854788a8a";
      sha256 = "11yxs0wqy70wj106fkz8r923yg4ncnc2mbw33v48zmlg4a1rasgp";
    };
  }
]
